enum ActionType {
  GET_CLUSTERS__REQUEST = 'GET_CLUSTERS__REQUEST',
  GET_CLUSTERS__SUCCESS = 'GET_CLUSTERS__SUCCESS',
  GET_CLUSTERS__FAILURE = 'GET_CLUSTERS__FAILURE',
}

export default ActionType;
