enum ActionType {
  CLUSTERS__FETCH_REQUEST = 'CLUSTERS__FETCH_REQUEST',
  CLUSTERS__FETCH_SUCCESS = 'CLUSTERS__FETCH_SUCCESS',
  CLUSTERS__FETCH_FAILURE = 'CLUSTERS__FETCH_FAILURE',
}

export default ActionType;
