enum ActionType {
  TOPICS__FETCH_REQUEST = 'TOPICS__FETCH_REQUEST',
  TOPICS__FETCH_SUCCESS = 'TOPICS__FETCH_SUCCESS',
  TOPICS__FETCH_FAILURE = 'TOPICS__FETCH_FAILURE',

  BROKERS__FETCH_REQUEST = 'BROKERS__FETCH_REQUEST',
  BROKERS__FETCH_SUCCESS = 'BROKERS__FETCH_SUCCESS',
  BROKERS__FETCH_FAILURE = 'BROKERS__FETCH_FAILURE',
}

export default ActionType;
