enum ActionType {
  GET_TOPICS__REQUEST = 'GET_TOPICS__REQUEST',
  GET_TOPICS__SUCCESS = 'GET_TOPICS__SUCCESS',
  GET_TOPICS__FAILURE = 'GET_TOPICS__FAILURE',

  GET_TOPIC_DETAILS__REQUEST = 'GET_TOPIC_DETAILS__REQUEST',
  GET_TOPIC_DETAILS__SUCCESS = 'GET_TOPIC_DETAILS__SUCCESS',
  GET_TOPIC_DETAILS__FAILURE = 'GET_TOPIC_DETAILS__FAILURE',
}

export default ActionType;
