version: '3'

services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:1.10.7
    volumes:
      - "../selenoid/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../selenoid/video:/video"
      - "../selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui:latest-release
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://localhost:4444" ]

  selenoid-chrome:
    network_mode: bridge
    image: selenoid/vnc:chrome_96.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
