package com.provectus.kafka.ui.util;

public enum JmxMetricsName {
  MessagesInPerSec,
  BytesInPerSec,
  ReplicationBytesInPerSec,
  RequestsPerSec,
  ErrorsPerSec,
  MessageConversionsPerSec,
  BytesOutPerSec,
  ReplicationBytesOutPerSec,
  NoKeyCompactedTopicRecordsPerSec,
  InvalidMagicNumberRecordsPerSec,
  InvalidMessageCrcRecordsPerSec,
  InvalidOffsetOrSequenceRecordsPerSec,
  UncleanLeaderElectionsPerSec,
  IsrShrinksPerSec,
  IsrExpandsPerSec,
  ReassignmentBytesOutPerSec,
  ReassignmentBytesInPerSec,
  ProduceMessageConversionsPerSec,
  FailedFetchRequestsPerSec,
  ZooKeeperSyncConnectsPerSec,
  BytesRejectedPerSec,
  ZooKeeperAuthFailuresPerSec,
  TotalFetchRequestsPerSec,
  FailedIsrUpdatesPerSec,
  IncrementalFetchSessionEvictionsPerSec,
  FetchMessageConversionsPerSec,
  FailedProduceRequestsPerSec
}
