#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


SRC_PATTERN="kafka-ui-react-app"
if git diff --cached --name-only | grep --quiet "$SRC_PATTERN"
then
  cd kafka-ui-react-app && npm run pre-commit
else 
  echo "Skipping frontend tests"
  exit 0
fi
