enum ActionType {
  GET_CLUSTERS__REQUEST = 'GET_CLUSTERS__REQUEST',
  GET_CLUSTERS__SUCCESS = 'GET_CLUSTERS__SUCCESS',
  GET_CLUSTERS__FAILURE = 'GET_CLUSTERS__FAILURE',

  GET_CLUSTER_STATS__REQUEST = 'GET_CLUSTER_STATUS__REQUEST',
  GET_CLUSTER_STATS__SUCCESS = 'GET_CLUSTER_STATUS__SUCCESS',
  GET_CLUSTER_STATS__FAILURE = 'GET_CLUSTER_STATUS__FAILURE',

  GET_CLUSTER_METRICS__REQUEST = 'GET_CLUSTER_METRICS__REQUEST',
  GET_CLUSTER_METRICS__SUCCESS = 'GET_CLUSTER_METRICS__SUCCESS',
  GET_CLUSTER_METRICS__FAILURE = 'GET_CLUSTER_METRICS__FAILURE',

  GET_BROKERS__REQUEST = 'GET_BROKERS__REQUEST',
  GET_BROKERS__SUCCESS = 'GET_BROKERS__SUCCESS',
  GET_BROKERS__FAILURE = 'GET_BROKERS__FAILURE',

  GET_BROKER_METRICS__REQUEST = 'GET_BROKER_METRICS__REQUEST',
  GET_BROKER_METRICS__SUCCESS = 'GET_BROKER_METRICS__SUCCESS',
  GET_BROKER_METRICS__FAILURE = 'GET_BROKER_METRICS__FAILURE',

  GET_TOPICS__REQUEST = 'GET_TOPICS__REQUEST',
  GET_TOPICS__SUCCESS = 'GET_TOPICS__SUCCESS',
  GET_TOPICS__FAILURE = 'GET_TOPICS__FAILURE',

  GET_TOPIC_MESSAGES__REQUEST = 'GET_TOPIC_MESSAGES__REQUEST',
  GET_TOPIC_MESSAGES__SUCCESS = 'GET_TOPIC_MESSAGES__SUCCESS',
  GET_TOPIC_MESSAGES__FAILURE = 'GET_TOPIC_MESSAGES__FAILURE',

  GET_TOPIC_DETAILS__REQUEST = 'GET_TOPIC_DETAILS__REQUEST',
  GET_TOPIC_DETAILS__SUCCESS = 'GET_TOPIC_DETAILS__SUCCESS',
  GET_TOPIC_DETAILS__FAILURE = 'GET_TOPIC_DETAILS__FAILURE',

  GET_TOPIC_CONFIG__REQUEST = 'GET_TOPIC_CONFIG__REQUEST',
  GET_TOPIC_CONFIG__SUCCESS = 'GET_TOPIC_CONFIG__SUCCESS',
  GET_TOPIC_CONFIG__FAILURE = 'GET_TOPIC_CONFIG__FAILURE',

  POST_TOPIC__REQUEST = 'POST_TOPIC__REQUEST',
  POST_TOPIC__SUCCESS = 'POST_TOPIC__SUCCESS',
  POST_TOPIC__FAILURE = 'POST_TOPIC__FAILURE',

  PATCH_TOPIC__REQUEST = 'PATCH_TOPIC__REQUEST',
  PATCH_TOPIC__SUCCESS = 'PATCH_TOPIC__SUCCESS',
  PATCH_TOPIC__FAILURE = 'PATCH_TOPIC__FAILURE',

  GET_CONSUMER_GROUPS__REQUEST = 'GET_CONSUMER_GROUPS__REQUEST',
  GET_CONSUMER_GROUPS__SUCCESS = 'GET_CONSUMER_GROUPS__SUCCESS',
  GET_CONSUMER_GROUPS__FAILURE = 'GET_CONSUMER_GROUPS__FAILURE',

  GET_CONSUMER_GROUP_DETAILS__REQUEST = 'GET_CONSUMER_GROUP_DETAILS__REQUEST',
  GET_CONSUMER_GROUP_DETAILS__SUCCESS = 'GET_CONSUMER_GROUP_DETAILS__SUCCESS',
  GET_CONSUMER_GROUP_DETAILS__FAILURE = 'GET_CONSUMER_GROUP_DETAILS__FAILURE',
}

export default ActionType;
