enum ActionType {
  GET_TOPICS__REQUEST = 'GET_TOPICS__REQUEST',
  GET_TOPICS__SUCCESS = 'GET_TOPICS__SUCCESS',
  GET_TOPICS__FAILURE = 'GET_TOPICS__FAILURE',

  GET_TOPIC_DETAILS__REQUEST = 'GET_TOPIC_DETAILS__REQUEST',
  GET_TOPIC_DETAILS__SUCCESS = 'GET_TOPIC_DETAILS__SUCCESS',
  GET_TOPIC_DETAILS__FAILURE = 'GET_TOPIC_DETAILS__FAILURE',

  GET_TOPIC_CONFIG__REQUEST = 'GET_TOPIC_CONFIG__REQUEST',
  GET_TOPIC_CONFIG__SUCCESS = 'GET_TOPIC_CONFIG__SUCCESS',
  GET_TOPIC_CONFIG__FAILURE = 'GET_TOPIC_CONFIG__FAILURE',

  POST_TOPIC__REQUEST = 'POST_TOPIC__REQUEST',
  POST_TOPIC__SUCCESS = 'POST_TOPIC__SUCCESS',
  POST_TOPIC__FAILURE = 'POST_TOPIC__FAILURE',
}

export default ActionType;
