enum ActionType {
  GET_BROKERS__REQUEST = 'GET_BROKERS__REQUEST',
  GET_BROKERS__SUCCESS = 'GET_BROKERS__SUCCESS',
  GET_BROKERS__FAILURE = 'GET_BROKERS__FAILURE',

  GET_BROKER_METRICS__REQUEST = 'GET_BROKER_METRICS__REQUEST',
  GET_BROKER_METRICS__SUCCESS = 'GET_BROKER_METRICS__SUCCESS',
  GET_BROKER_METRICS__FAILURE = 'GET_BROKER_METRICS__FAILURE',
}

export default ActionType;
