auth:
  enabled: true
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [put your client id here]
            client-secret: [put your client secret here]
