name: Release-helm
on: push
# push:
#   paths:
#      - "charts/kafka-ui/**"

jobs:
 release:
  runs-on:
   ubuntu-latest
  steps:
      - uses: actions/checkout@v3
      - name: Helm tool installer
        uses: Azure/setup-helm@v1
      - name: Setup Kubeval
        uses: lra/setup-kubeval@v1.0.1
      - name: Check version
        shell: bash
        run: |
          git branch
          git checkout master
          helm_version_old=$(cat chatrs/kafka-ui/Chart.yaml  | grep version | awk  '{print $2}')
          git checkout helm-versioning
          helm_version_new=$(cat chatrs/kafka-ui/Chart.yaml  | grep version | awk  '{print $2}')
          echo $helm_version_old
          echo $helm_version_new   
      - name: Run kubeval
        shell: bash
        run: |
          sed -i "s@enabled: false@enabled: true@g" charts/kafka-ui/values.yaml
          K8S_VERSIONS=$(git ls-remote --refs --tags https://github.com/kubernetes/kubernetes.git | cut -d/ -f3 | grep -e '^v1\.[0-9]\{2\}\.[0]\{1,2\}$' | grep -v -e  '^v1\.1[0-7]\{1\}' | cut -c2-)
          echo "NEXT K8S VERSIONS ARE GOING TO BE TESTED: $K8S_VERSIONS"
          echo ""
          for version in $K8S_VERSIONS
            do
              echo $version;
              helm template --kube-version $version --set ingress.enabled=true charts/kafka-ui -f charts/kafka-ui/values.yaml | kubeval --additional-schema-locations https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master --strict -v $version;
            done


       
