name: Release-helm
on:
 push:
    branches:
     - master
    paths:
      - "charts/**"

jobs:
 release:
  runs-on:
   ubuntu-latest
  steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: azure/setup-helm@v1

      - name: add chart
        run: |
          MSG=$(helm package  charts/kafka-ui)
          git fetch origin
          git stash
          git checkout -b gh-pages origin/gh-pages
          helm repo index .
          git add -f ${MSG##*/} index.yaml
          git commit -m "release VERSION"
          git push