name: "PR: Checklist linter"
on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]
permissions:
  checks: write
jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: dekinderfiets/pr-description-enforcer@0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
