name: Release helm
on:
 push:
    branches:
     - master
    paths:
      - "charts/**"

jobs:
 release-helm:
  runs-on:
   ubuntu-latest
  steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: azure/setup-helm@v1

      - name: add chart
        run: |
          echo "VERSION=$(cat charts/kafka-ui/Chart.yaml  | grep version | awk '{print $2}')" >> $GITHUB_ENV
          MSG=$(helm package  charts/kafka-ui)
          git fetch origin
          git stash
          git checkout -b gh-pages origin/gh-pages
          helm repo index .
          git add -f ${MSG##*/} index.yaml
          git commit -m "release ${{ env.VERSION }}"
          git push        
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "charts/kafka-ui-${{ env.VERSION }}"    