name: after_release
on:
  push:
    tags:
      - "v**"
jobs:
  charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: azure/setup-helm@v1
      - name: update appVersion
        run: |
          export version=${GITHUB_REF##*/}
          sed -i "s/appVersion:.*/appVersion: ${version}/" charts/kafka-ui/Chart.yaml
      - name:
        run: |
          export VERSION=${GITHUB_REF##*/}
          MSG=$(helm package --app-version ${VERSION} charts/kafka-ui)
          git fetch origin
          git stash
          git checkout -b gh-pages origin/gh-pages
          helm repo index .
          git add -f ${MSG##*/} index.yaml
          git commit -m "release ${VERSION}"
          git push
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - id: generate
        shell: /usr/bin/bash -x -e {0}
        run: |
          VERSION=${GITHUB_REF##*/}
          CHANGELOG=$(git --no-pager log --oneline --pretty=format:"- %s" `git tag --sort=-creatordate | grep '^v.*' | head -n2 | tail -n1`.. | uniq | grep -v '^- Merge\|^- skip')
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo ${CHANGELOG}
          echo "::set-output name=changelog::${CHANGELOG}"
          echo "::set-output name=version::${VERSION}"
      - name: Download release JAR
        uses: actions/download-artifact@v2
        with:
          name: kafka-ui-${{ steps.generate.outputs.version }}
          path: kafka-ui-${{ steps.generate.outputs.version }}.jar
      - id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{steps.generate.outputs.version}}
          draft: false
          prerelease: false
          file: kafka-ui-${{ steps.generate.outputs.version }}.jar
          body: ${{steps.generate.outputs.changelog}}