name: Triage label new issues
on:
  issues:
    types:
      - opened
jobs:
  triage_label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues
        uses: andymckay/labeler@master
        with:
          add-labels: "status/triage"
          ignore-if-assigned: true
