name: Add triage label to new issues
on:
  issues:
    types:
      - opened
jobs:
  triage_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label issue
        uses: andymckay/labeler@master
        with:
          add-labels: "status/triage"
          ignore-if-assigned: true
