name: Add triage label to new PRs
on:
  pull_request:
    types:
      - opened
jobs:
  triage_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: andymckay/labeler@master
        with:
          add-labels: "status/triage"
          ignore-if-labeled: true
